name: mfcc
version: 1.1.0
homepage: https://github.com/Lokhozt/mfcc
description: A library written in Dart to extract Mel-Frequency Cepstral Coefficients (MFCCs) from a signal.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  fft: ^0.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
